# This is a basic workflow to help you get started with Actions

name: Test Eslint


on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    runs-on: ubuntu-latest
    

steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
      - uses: actions/setup-node@v1
        run: make install
      - name: test
        run: make lint
