# This is a basic workflow to help you get started with Actions

name: Test Eslint


on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-job:
    runs-on: ubuntu-latest
    
strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      - name: npm install
        run: make install
        run: make lint
